//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Project_Ex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoptopData
    {
        public int Id { get; set; }
        public string LopId { get; set; }
        public string Lopname { get; set; }
        public string LopModel { get; set; }
        public string LopDetails { get; set; }
        public int Lopprice { get; set; }
        public string LopUrl { get; set; }
    }
}
