//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Project_Ex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobData
    {
        public int Id { get; set; }
        public int MobId { get; set; }
        public string Mobname { get; set; }
        public int Price { get; set; }
        public string Desription { get; set; }
        public string ZoomUrl { get; set; }
        public string Url { get; set; }
    }
}
